diffusionx/urls.py
from django.conf.urls import url

from . import views
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/img/favicon.png', permanent=True)

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_view, name='login_view'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^register/', views.register),
    url(r'^experiment/$', views.experiment_list, name='experiment_list'),
    url(r'^experiment/step/1$', views.step1, name='step1'),
    url(r'^experiment/step/2$', views.step2),
    url(r'^experiment/step/3$', views.step3),
    url(r'^experiment/state/1$', views.step1_state),
    url(r'^experiment/state/2$', views.step2_state),
    url(r'^experiment/state/3$', views.step3_state),
    url(r'^experiment/state/submit$', views.run_experiment),
    url(r'^experiment/new$', RedirectView.as_view(url='/experiment/step/1', permanent=False), name='experiment_new'),
    url(r'^experiment/(?P<pk>\d+)$', views.experiment_detail, name='experiment_detail'),
    url(r'^experiment/(?P<pk>\d+)/delete$', views.experiment_delete, name='experiment_delete'),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^network/$', views.network_list, name='network_list'),
    url(r'^network/new$', views.network_new, name='network_new'),
    url(r'^network/(?P<pk>\d+)$', views.network_detail, name='network_detail'),
    url(r'^network/(?P<pk>\d+)/delete$', views.network_delete, name='network_delete'),
    url(r'^get_json_graph/(?P<pk>\d+)$', views.get_json_graph),
    url(r'^graph/(\d+)/$', views.network_graph),
    url(r'^diffusion/(?P<pk>\d+)$', views.diffusion, name='diffusion'),
    url(r'^diffusion/(?P<pk>\d+)/delete$', views.diffusion_delete, name='diffusion_delete'),
    url(r'^get_json_diffusion/(?P<pk>\d+)$', views.get_json_diffusion),
]

information_diffusion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import diffusionx.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^password_change$', auth_views.password_change, name='password_change'),
    url(r'^password_change_done$', auth_views.password_change_done, name='password_change_done'),
    url(r'^', include(diffusionx.urls, namespace="diffusionx")),
]

diffusionx/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.postgres.fields import JSONField
from networkx import is_directed
from networkx.readwrite import json_graph
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Network(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    nodes = models.IntegerField()
    edges = models.IntegerField()
    directed = models.BooleanField()
    added_at = models.DateTimeField()
    graph = JSONField()

    def __str__(self):
        return self.name

    # extract network model attributes from networkX graph and save a new model instance
    def save_nx_graph(self, graph_data, network_name, user):
        self.user = user
        self.directed = is_directed(graph_data)
        self.nodes = graph_data.number_of_nodes()
        self.edges = graph_data.number_of_edges()
        self.graph = json_graph.node_link_data(graph_data)
        self.added_at = timezone.now()
        self.name = network_name
        self.save()

    def get_nx_graph(self):
        return json_graph.node_link_graph(self.graph)


class Experiment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    started_at = models.DateTimeField()


class Diffusion(models.Model):
    DIFFUSION_MODELS = (
        ('ltm', 'Linear Threshold Model'),
        ('icm', 'Independent Cascade Model')
    )
    network = models.ForeignKey(Network, on_delete=models.CASCADE)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    model = models.CharField(
        max_length=128,
        choices=DIFFUSION_MODELS
    )
    model_param = models.CharField(max_length=64)
    steps = models.IntegerField()
    cover = models.FloatField()
    seed_criteria = models.CharField(max_length=128)
    seed_value = models.CharField(max_length=16)
    diffusion_steps = JSONField()


@receiver(models.signals.post_delete, sender=Diffusion)
def delete_empty_experiment(sender, instance, *args, **kwargs):
    experiment_id = instance.experiment_id
    if Experiment.objects.filter(id=experiment_id).exists() and not Diffusion.objects.filter(
            experiment_id=experiment_id).count():
        experiment_object = Experiment.objects.get(pk=experiment_id)
        experiment_object.delete()

diffusionx/views.py
import json
import logging
import os.path
from tempfile import NamedTemporaryFile

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count
from django.forms import ValidationError
from django.http import HttpResponseRedirect, Http404, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.safestring import mark_safe

import diffusionx.experiment as exp
from diffusionx.diffusion_conf import network_types, seed_criteria
from diffusionx.file_handler import handle_csv_data
from diffusionx.konect_crawler import konect_network
from diffusionx.models import Network, Experiment, Diffusion
from information_diffusion.settings import MAX_GRAPH_UPLOAD_SIZE
from .forms import UserRegistrationForm, LoginForm


def index(request):
    if request.user.is_authenticated:
        networks_number = Network.objects.filter(user=request.user).count()
        experiments_number = Experiment.objects.filter(user=request.user).count()
    else:
        networks_number = 0
        experiments_number = 0

    return render(request, 'diffusionx/index.html',
                  {'networks_number': networks_number, 'experiments_number': experiments_number})


@login_required
def experiment(request):
    return redirect('/experiment/step/1')


@login_required
def step1(request):
    saved_networks = request.session.get('nt', None)

    select_networks = Network.objects. \
        values_list('id', 'name', 'nodes', 'edges', 'added_at', 'directed').filter(user=request.user)
    chosen_networks = []

    if saved_networks:
        saved_networks = list(map(int, saved_networks))
        chosen_networks = [x for x in select_networks if x[0] in saved_networks]
        select_networks = [x for x in select_networks if x[0] not in saved_networks]

    return render(request, 'diffusionx/experiments/steps/step_1.html',
                  {'select_list': select_networks, 'chosen_list': chosen_networks, 'step': 1})


@login_required
def step1_state(request):
    if request.is_ajax():
        if request.method == 'POST':
            chosen_networks = request.POST.getlist('networks[]')
            request.session['nt'] = chosen_networks
            return HttpResponse('Success')

    return HttpResponse(status=405)


@login_required
def step2(request):
    seed_selection_criteria = [(sc['id'], sc['name']) for sc in seed_criteria]
    return render(request, 'diffusionx/experiments/steps/step_2.html',
                  {'seed_criteria': seed_selection_criteria, 'step': 2})


@login_required
def step2_state(request):
    if request.is_ajax():
        if request.method == 'POST':
            json_data = json.loads(request.body)
            request.session['seed'] = json_data
            return HttpResponse('Success')
        elif request.method == 'GET':
            json_data = request.session.get('seed', [])
            return JsonResponse(json_data, safe=False)

    return HttpResponse(status=405)


@login_required
def step3(request):
    return render(request, 'diffusionx/experiments/steps/step_3.html', {'step': 3})


@login_required
def step3_state(request):
    if request.is_ajax():
        if request.method == 'POST':
            json_data = json.loads(request.body)
            request.session['models'] = json_data
            return HttpResponse('Success')
        elif request.method == 'GET':
            json_data = request.session.get('models', [])
            return JsonResponse(json_data, safe=False)

    return HttpResponse(status=405)


@login_required
def run_experiment(request):
    networks = request.session['nt']
    seed = request.session['seed']
    models = request.session['models']
    current_user = request.user

    if len(networks) == 0 or len(seed) == 0 or len(models) == 0:
        messages.error(request, 'Invalid data. Not all properties are specified')
        return redirect('diffusionx:experiment_new')

    exp.run_experiment(networks=networks, seed=seed, models=models, user=current_user)
    del request.session['nt']
    del request.session['seed']
    del request.session['models']
    messages.success(request, "Experiment  successfully completed")

    return redirect('diffusionx:experiment_list')


def login_view(request):
    form = LoginForm(request.POST or None)
    if request.POST and form.is_valid():
        user = form.login(request)
        if user:
            login(request, user)
            return HttpResponseRedirect("/")
        else:
            messages.error(request, "Bad credentials")

    if request.user.is_authenticated():
        return HttpResponseRedirect("/")
    else:
        return render(request, 'registration/login.html', {'login_form': form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user_obj = form.cleaned_data
            username = user_obj['username']
            email = user_obj['email']
            password = user_obj['password']
            bio = user_obj['bio']

            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username is already taken.')
            elif User.objects.filter(email=email).exists():
                messages.error(request, 'Email address is already taken.')
            else:
                user = User.objects.create_user(username, email, password)
                user.refresh_from_db()
                user.profile.bio = bio
                user.save()
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/')

    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def network_graph(request, graph_type):
    type_id = int(graph_type)
    if 0 <= type_id <= len(network_types):
        form = network_types[type_id]['form']()
        return render(request, 'diffusionx/networks/network_graph.html', {'form': form})


def _save_network_graph(request, graph, graph_name):
    network = Network()
    if graph.number_of_nodes():
        network.save_nx_graph(graph_data=graph, user=request.user,
                              network_name=graph_name)
        messages.success(request, "Graph successfully added")
    else:
        messages.error(request, "Graph is empty")


@login_required
def network_new(request):
    if request.POST:
        network_selection = int(request.POST.get("network-select"))

        if network_selection == 1:
            try:
                upload = request.FILES["file"]
                extension = os.path.splitext(upload.name)[1].lower()
                if extension not in ['.csv', '.edgelist', '.mtx', '.edges', '.tsv']:
                    messages.error(request, 'The file type (%d) is not supported' % extension)
                    return HttpResponseRedirect(reverse("diffusionx:network_new"))

                delimiter = request.POST.get('delimiter', None)
                comments = request.POST.get('comments')
                directed = True if 'directed' in request.POST else False
                edge_type = request.POST.get('edgetype', 'none')

                # file cannot be too large
                if upload.size > MAX_GRAPH_UPLOAD_SIZE:
                    messages.error(request, "Uploaded file is too big (%.2f MB).Max. allowed size is 500MB."
                                   % (upload.size / (1000 * 1000),))
                    return HttpResponseRedirect(reverse("diffusionx:network_new"))

                f = NamedTemporaryFile(delete=False)
                path = f.name
                for chunk in upload.chunks():
                    f.write(chunk)
                f.close()

                if comments:
                    graph = handle_csv_data(path, delimiter=delimiter, comments=comments, directed=directed,
                                            edge_type=edge_type)
                else:
                    graph = handle_csv_data(path, delimiter=delimiter, directed=directed,
                                            edge_type=edge_type)

                _save_network_graph(request, graph, graph_name=request.POST['network_name'])
                os.unlink(path)
                return redirect('diffusionx:network_list')
            except Exception as e:
                logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
                messages.error(request, "Unable to upload file. " + repr(e))
        elif network_selection == 2:
            graph_model = int(request.POST['random-graph'])
            mutable_dict = request.POST.copy()
            graph_name = mutable_dict.pop('network_name')[0]
            graph_form = network_types[graph_model]['form']

            form = graph_form(mutable_dict)
            if form.is_valid():
                try:
                    graph = form.get_network()
                    _save_network_graph(request, graph, graph_name)
                    return redirect('diffusionx:network_list')
                except ValidationError as error:
                    messages.error(request, error.message)
            else:
                messages.error(request, "Invalid form")
        elif network_selection == 3:
            konect_url = request.POST['konect-url']
            try:
                graph = konect_network(konect_url)
                _save_network_graph(request, graph, graph_name=request.POST['network_name'])
                return redirect('diffusionx:network_list')
            except Exception as e:
                messages.error(request, e)

diffusionx/templates/diffusionx/experiments/diffusion.html
{% extends "diffusionx/layout.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'bower_components/c3/c3.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/diffusion.css' %}">
{% endblock %}

{% block content %}
    <div id="details-card" class="col-centered diffusion-card card">
        <div class="card-body">
            <h4 class="card-title">Diffusion details</h4>
            <form method="POST" class="delete-button-form" action="/diffusion/{{ data.id }}/delete">
                {% csrf_token %}
                <button class="btn btn-xs btn-danger" type="button" data-toggle="modal"
                        data-target="#confirm-dialog"
                        data-title="Delete diffusion"
                        data-message="Are you sure you want to delete this diffusion?">
                    <i class="fa fa-trash" aria-hidden="true"></i> Delete
                </button>
            </form>
            <table class="table">
                <tr>
                    <th>Network name</th>
                    <td><a href="/network/{{ data.network_id }}">{{ data.network.name }}</a></td>
                </tr>
                <tr>
                    <th>Diffusion model</th>
                    <td>{{ data.get_model_display }}</td>
                </tr>
                <tr>
                    <th>Model parameter</th>
                    <td>{{ data.model_param }}</td>
                </tr>
                <tr>
                    <th>Seed criteria</th>
                    <td>{{ data.seed_criteria }}</td>
                </tr>
                <tr>
                    <th>Seed value</th>
                    <td>{{ data.seed_value }}</td>
                </tr>
                <tr>
                    <th>Diffusion steps</th>
                    <td>{{ data.steps }}</td>
                </tr>
                <tr>
                    <th>Final cover ratio</th>
                    <td>{{ data.cover }}</td>
                </tr>
                <tr>
                    <th>All nodes</th>
                    <td>{{ data.network.nodes }}</td>
                </tr>
            </table>
        </div>
    </div>


    <div class="col-centered diffusion-card card">
        <button id="animation-start" class="btn btn-success">Start</button>
        <div class="row animation-status">
            <div class="col-6">
                <label>Animation speed</label>
                <br/>
                <input id="step-time" class="reversed-slider" type="range" min="100" max="3100" value="1000" step="250">
            </div>
            <div class="col-2">
                <span class="diffusion-step-status">Step <span class="status-value">1</span></span></div>
            <div class="col-2">
                <span class="active-nodes-status">Active <span class="status-value">...</span></span>
            </div>
            <div class="col-2">
                <span class="cover-status">Cover <span class="status-value">...</span></span>
            </div>
        </div>


        <div id="graph-window" class="col-md-12">
            <svg width="500" height="500"></svg>
        </div>


    </div>

    <div class="col-centered diffusion-card card">
        <div class="row">
            <div class="col-md-6">
                <div id="line-chart">
                </div>
            </div>
            <div class="col-md-6">
                <div id="pie-chart">
                </div>
            </div>
        </div>
    </div>

    {% include "diffusionx/includes/confirm_dialog.html" %}
{% endblock %}

{% block js-code %}
    {{ block.super }}
    <script src="{% static 'bower_components/d3/d3.min.js' %}"></script>
    <script src="{% static 'js/force-directed-graph.js' %}"></script>
    <script src="{% static 'bower_components/c3/c3.min.js' %}"></script>
    <script type="text/javascript">
        initConfirmDialog();

        //graph animation settings
        var currentGraphSize = {{ data.network.nodes }};
        var networkId = {{ data.network.id }};

        drawGraph(currentGraphSize, networkId);

        stepTime = 1000;
        changeColorDuration = 300;
        diffusionId = {{ data.id }};
        getDiffusions();

        $('#animation-start').click(function () {
            runAnimation();
        });

        $('#step-time').change(function () {
            stepTime = this.value;
        });
    </script>
    <script>
        var chart = c3.generate({
            bindto: '#line-chart',
            data: {
                columns: [
                    {{ steps }},
                    {{ steps_sum }}
                ]
            }
        });
        var pieChart = c3.generate({
            bindto: '#pie-chart',
            data: {
                columns: [
                    ['active nodes', {{ active_nodes }}],
                    ['nonactive nodes', {{ nonactive_nodes }}]
                ],
                type: 'pie'
            }
        });
    </script>

{% endblock %}

diffusionx/templates/diffusionx/experiments/experiment.html
{% extends "diffusionx/layout.html" %}

{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/experiment_form.css' %}">
{% endblock %}

{% block content %}
    <div id="nav-field">
        <div>
            <div class="left-title-steps">
                <button id="previousStep" class="btn btn-steps btn-secondary disabled">PREVIOUS</button>
            </div>
            <div class="right-title-steps" style="float: right">
                <button id="nextStep" class="btn btn-primary btn-steps">NEXT</button>
            </div>
            <div class="center-title-steps unselectable"><h2>NEW EXPERIMENT</h2></div>
        </div>
        <div class="steps clearfix unselectable">
            <ul>
                <li class="tab-experiment">
                    <a>1. Load network</a>
                </li>
                <li class="tab-experiment">
                    <a>2. Choose seed</a>
                </li>
                <li class="tab-experiment">
                    <a>3. Diffusion model</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="container">
        {% block step-content %}
        {% endblock %}
    </div>

{% endblock %}

{% block js-code %}
    {{ block.super }}
    <script>
        var step = {{ step }};
    </script>
    <script src="{% static 'js/step1.js' %}"></script>
    <script src="{% static 'js/step2.js' %}"></script>
    <script src="{% static 'js/step3.js' %}"></script>
    <script src="{% static 'js/experiment.js' %}"></script>
{% endblock %}

diffusionx/templates/diffusionx/experiments/experiment_detail.html
{% extends "diffusionx/layout.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/experiments.css' %}">
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6"><h2 class="display-4 align-table-margin">Experiment</h2></div>
            <div class="col-md-6">
                <form method="POST" class="delete-button-form" action="/experiment/{{ experiment_id }}/delete">
                    {% csrf_token %}
                    <button class="btn btn-xs btn-danger" type="button" data-toggle="modal"
                            data-target="#confirm-dialog"
                            data-title="Are you sure you want to delete this experiment?"
                            data-message="Warning! Dependent diffusions would be deleted with the experiment.">
                        <i class="fa fa-trash" aria-hidden="true"></i> Delete
                    </button>
                </form>
            </div>
        </div>
        <div id="experiment-info-box">
            <p><span class="info-header">Experiment started at:</span> {{ started_at }}</p>
            <p><span class="info-header">Number of diffusions:</span> {{ object_list|length }}</p>
        </div>
        <table class="table table-striped" id="diffusions-table">
            <thead class="thead-mint">
            <tr>
                <th>#</th>
                <th>Network</th>
                <th>Model</th>
                <th>Model parameters</th>
                <th>Seed criteria</th>
                <th>Seed value</th>
                <th>Cover</th>
                <th>Steps</th>
            </tr>
            </thead>
            <tbody>
            {% for diffusion in object_list %}
                <tr class='clickable-row' data-href='/diffusion/{{ diffusion.id }}'>
                    <td>{{ diffusion.id }}</td>
                    <td><a href='/network/{{ diffusion.network.id }}'>{{ diffusion.network.name }}</a></td>
                    <td>{{ diffusion.get_model_display }}</td>
                    <td>{{ diffusion.model_param }}</td>
                    <td>{{ diffusion.seed_criteria }}</td>
                    <td>{{ diffusion.seed_value }}</td>
                    <td>{{ diffusion.cover }}</td>
                    <td>{{ diffusion.steps }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="8" class="text-center bg-warning">No experiment</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "diffusionx/includes/confirm_dialog.html" %}
{% endblock %}

{% block js-code %}
    {{ block.super }}
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables-datetime-moment/dist/js/datetime-moment.min.js' %}"></script>
    <script type="text/javascript">
        initConfirmDialog();

        //Datatables settings
        var t = $('#diffusions-table').DataTable({
            "columnDefs": [{
                "searchable": false,
                "orderable": false,
                "targets": 0
            }],
            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
            //add click listeners every time datatable is redrawn
            "fnDrawCallback": function () {
                $(".clickable-row").click(function () {
                    window.location = $(this).data("href");
                });
            }
        });

        //number rows according to their order
        t.on('order.dt search.dt', function () {
            t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
    </script>
{% endblock %}

diffusionx/templates/diffusionx/experiments/experiment_list.html
{% extends "diffusionx/layout.html" %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/experiments.css' %}">
{% endblock %}
{% block content %}
    <div class="col-md-12">
        <h1 class="display-4 text-center">Your experiments</h1>
        <div id="new-experiment-btn-container" class="align-table-margin">
            <a href="/experiment/new" class="btn btn-success"><i class="fas fa-plus"></i> Add experiment</a>
        </div>
        <table class="table table-dark table-striped" id="experiments-table">
            <thead>
            <tr>
                <th>#</th>
                <th>Started at</th>
                <th>Diffusions</th>
            </tr>
            </thead>
            <tbody>
            {% for experiment in object_list %}
                <tr class='clickable-row' data-href='{{ experiment.0 }}'>
                    <td>{{ experiment.0 }}</td>
                    <td>{{ experiment.1 | date:"H:i, M d, Y" }}</td>
                    <td>{{ experiment.2 }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3" class="text-center bg-warning">No experiment</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block js-code %}
    {{ block.super }}
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables-datetime-moment/dist/js/datetime-moment.min.js' %}"></script>
    <script>
        $.fn.dataTable.moment('HH:mm, MMM DD, YYYY');

        var t = $('#experiments-table').DataTable({
            "columnDefs": [{
                "searchable": false,
                "orderable": false,
                "targets": 0
            }],
            "order": [[1, 'desc']],
            "lengthMenu": [[10, 20, 30, -1], [10, 20, 30, "All"]],
            //add click listeners every time datatable is redrawn
            "fnDrawCallback": function () {
                $(".clickable-row").click(function () {
                    window.location = $(this).data("href");
                });
            }
        });

        //number rows according to their order
        t.on('order.dt search.dt', function () {
            t.column(0, {search: 'applied', order: 'applied'}).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
    </script>
{% endblock %}